### ISSUE TITLE
missing commune values

### ISSUE THREAD

**Issue by okilimu** [grischard/csventrifuge#1]
Hello,

i use your converted csv-file luxembourg-addresses.csv for housenumber evaluation in osm.

There are some lines with empty commune entries,  for example

`Maison	1	Mecher	9765	3692	196082	50.039489428142353	6.0154462785633305	69062.063499999698	122822.83466114622	025C00839003265_3692_1
Maison	1	Wirtgensmühle	9765	9074	232013	50.033562841610539	6.0087858007623272	68583.526608306827	122164.60759999999	025C00857001282_9074_1
Maison	1	Kaaspelterhof	9765	9072	237812	50.028993063318033	6.0000902373431702	67959.385499999844	121657.66600000022	025C00891003025_9072_1
Maison	1	Kirelshof	9759	9073	232011	50.028768843015939	5.9728220880837597	66005.474000000395	121637.44989864671	025C01018003185_9073_1
`
and i don't have my own translation from Mecher to the correct commune.

Will you fill in the missing commune entries in the future?

I ignore this adresses with empty commune, is it ok?

Greetings, Dietmar
Admin at regio-osm.de housenumber evaluations

**Comment by grischard** [comment]
Thanks Dietmar!

Two issues here:

1. Some places have changed names in the list, so the commune can't easily be looked up anymore
2. Csventrifuge fails silently when it can't find an enhancement.

I have added the error reporting locally, and will commit once I have the correct commune for these villages:

Erpeldange
Fischbach
Kaaspelterhof
Kirelshof
Mecher
Roodt-sur-Eisch
Weyer
Wirtgensmühle

**Comment by grischard** [comment]
Every address has a commune now. Thanks again!
